modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[3.3.7,)"
ordering = "AFTER"
side = "BOTH"